name: Deploy IaC - HCL
defaults:
  run:
    working-directory: iac
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment.'
        required: true
        default: production
        type: choice
        options:
          - development
          - production
      aws_region:
        description: 'Deployment Region for infra and tfstate bucket.'
        required: true
        default: us-east-1
      action:
        description: 'Action to perform'
        required: true
        default: plan
        type: choice
        options:
          - plan
          - deploy
          - destroy
      bucket_name:
        description: 'AWS S3 bucket name'
        required: true
        default: mybuckett21000

env:
  AWS_REGION: ${{ github.event.inputs.aws_region || 'us-east-1' }}
  BUCKET_NAME: ${{ github.event.inputs.bucket_name }}
  TF_VERSION: 1.5.0

jobs:
  plan:
    if: ${{ github.event.inputs.environment == 'production' || github.event.inputs.action == 'plan' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.BUCKET_NAME }}" \
            -backend-config="key=turbovets/${{ github.event.inputs.environment }}/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars"

  deploy:
    needs: plan
    if: ${{ !failure() && !cancelled() && github.event.inputs.action == 'deploy'}}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.BUCKET_NAME }}" \
            -backend-config="key=turbovets/${{ github.event.inputs.environment }}/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Deploy The Infrastructure
        run: terraform apply -var-file="${{ github.event.inputs.environment }}.tfvars" -auto-approve

  destroy:
    if: ${{ github.event.inputs.action == 'destroy' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.BUCKET_NAME }}" \
            -backend-config="key=turbovets/${{ github.event.inputs.environment }}/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Destroy The Infrastructure
        run: terraform destroy -var-file="${{ github.event.inputs.environment }}.tfvars" -auto-approve