name: Deploy IaC (manual)
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment.'
        required: true
        default: development
        type: choice
        options:
          - development
          - production
      aws_region:
        description: 'Deployment Region.'
        required: true
        default: us-east-1
        
jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: 1.14.4

      - name: Install & build (iac)
        working-directory: iac
        run: |
          npm install
          npm run build

      - name: CDKTF get providers
        working-directory: iac
        run: npx cdktf get

      - name: CDKTF synth
        working-directory: iac
        run: npx cdktf synth

      - name: Generate plan JSON
        working-directory: iac
        run: npx cdktf diff --json > plan.json

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: cdktf-plan
          path: iac/plan.json

      - name: Show plan in logs
        working-directory: iac
        run: cat plan.json
  
  deploy:
    needs: plan
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      CI: 'true'
      TERM: xterm-256color

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: 1.14.4

      - name: Install & build (iac)
        working-directory: iac
        run: |
          npm install
          npm run build

      - name: CDKTF get providers
        working-directory: iac
        run: npx cdktf get

      - name: CDKTF synth
        working-directory: iac
        run: npx cdktf synth
        
      - name: Deploy using pre-generated plan
        working-directory: iac
        run: npx cdktf deploy --auto-approve
        
      - name: Show outputs
        working-directory: iac
        run: npx cdktf output -json || true
